### ISSUE TITLE
fatal error when running example

### ISSUE THREAD

**Issue by ashemsay** [ev3go/ev3dev#82]
Hello,
I am having some trouble making the example run.

What I did on my computer:

* Set GOARCH to arm
* Set GOARM to 5
* Set GOOS to linux

```bash
go get github.com/ev3go/ev3dev/examples/demo 
go build github.com/ev3go/ev3dev/examples/demo 
scp demo robot@x.x.x.x:/home/robot
```
What I did on the robot:

* Run the demo program through the LCD interface on the brick: does nothing but displays some text for a fraction of a second
* Run the demo program from an ssh session on the robot `./demo`.
  This is what it returns:

```bash
robot@ev3dev:~$ ./demo
unexpected fault address 0xa6c92000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0xa6c92000 pc=0x63dd4]

goroutine 1 [running]:
runtime.throw(0xe8bd5, 0x5)
	/usr/local/go/src/runtime/panic.go:608 +0x5c fp=0x424668 sp=0x424654 pc=0x38990
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:387 +0x214 fp=0x42468c sp=0x424668 pc=0x4bfb0
runtime.memclrNoHeapPointers(0xa6c91000, 0x16400)
	/usr/local/go/src/runtime/memclr_arm.s:68 +0x58 fp=0x424690 sp=0x424690 pc=0x63dd4
github.com/ev3go/ev3dev.(*lcd).frameBuffer(0x472000, 0xf0b01, 0x472018, 0x66)
	/home/lionel/Documents/projects/go/src/github.com/ev3go/ev3dev/lcd.go:85 +0x1c0 fp=0x4246cc sp=0x424690 pc=0xb8774
github.com/ev3go/ev3dev.(*lcd).Init(0x472000, 0x1, 0x0, 0x0)
	/home/lionel/Documents/projects/go/src/github.com/ev3go/ev3dev/lcd.go:60 +0x10c fp=0x4246e4 sp=0x4246cc pc=0xb8578
main.main()
	/home/lionel/Documents/projects/go/src/github.com/ev3go/ev3dev/examples/demo/demo.go:26 +0x38 fp=0x4247c4 sp=0x4246e4 pc=0xbb970
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x204 fp=0x4247e4 sp=0x4247c4 pc=0x3a584
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0x4247e4 sp=0x4247e4 pc=0x636d8
```

I compiled a simple hello world program to make sure the problem was not from the compilation and it worked perfectly.

Could you help me please?

Note: I am  using the jessie version ev3dev-jessie-ev3-generic-2017-09-14

**Comment by ashemsay** [comment]
Hum I feel stupid, I indeed read the README but obviously did not pay enough attention while doing so.
I did checkout the `ev3dev-jessie` branch in both ev3go/ev3dev et ev3go/ev3 and it worked as expected.

Sorry about that and thank you for your quick reply.
